name: GitHub Actions CI workflow

on: [push, pull_request]

jobs:
  lint: 
    name: code style lint
    runs-on: ubuntu-latest
    steps:

      # checkout new code
      - name: checkout
        uses: actions/checkout@v2

      # install node 
      - name: use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: use yarn
        run: npm install -g yarn

      - name: install dependencies
        run: yarn

      - name: eslint
        run: yarn run lint:fix
      
      - name: prettier
        run: yarn run prettier

      # # use yarn && install dependencies
      # - name: use yarn && install dependencies
      #   uses: borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: install

      
      # # eslint
      # - name: eslint
      #   uses: borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: lint:fix

      # # prettier
      # - name: prettier
      #   uses: borales/actions-yarn@v2.3.0
      #   with:
      #     cmd: prettier
      #   # run: yarn run prettier

     